import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import localFont from "next/font/local";
import { Toaster } from "@/components/ui/toaster";
import { currentUser } from "@clerk/nextjs/server";
import { Suspense } from "react";
import NavbarSkeleton from "@/components/loading/NavbarSkeleton";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {

	return (
		<ClerkProvider
			appearance={{
				layout: {
					unsafe_disableDevelopmentModeWarnings: true,
				},
				elements: {
					footer: {
						display: "none",
					},
				},
			}}>
			<html lang="en">
				<body className={`${geistSans.variable} ${geistMono.variable} bg-[#f2f2f2] antialiased`}>
					<Suspense fallback={<NavbarSkeleton />}>
						<Navbar />
					</Suspense>
					{children}
					<Toaster />
				</body>
			</html>
		</ClerkProvider>
	);
}
